### ISSUE TITLE
请问原来是涂鸦智能的485协议地暖如何改成米家的呢

### ISSUE THREAD

**Issue by MAOGE2018** [idreamshen/esphome-demry-vrf#2]
![IMG_20231112_170759](https://github.com/idreamshen/esphome-demry-vrf/assets/39059232/f576f173-1ac6-40ea-9159-4f61a7b1cd76)
![IMG_20231112_144040](https://github.com/idreamshen/esphome-demry-vrf/assets/39059232/d4828053-4c18-4fab-864c-ee7eb997ac24)
![地暖分水器实物图](https://github.com/idreamshen/esphome-demry-vrf/assets/39059232/3e26bb92-f38c-483e-8944-0ef46c4d7d81)
[地暖接线实物图.pdf](https://github.com/idreamshen/esphome-demry-vrf/files/13533226/default.pdf)

https://www.edrawmax.cn/online/share.html?code=d88b2df2541a11ed8a0c173c5440fe6f

**Comment by idreamshen** [comment]
问题与本仓库无关
